### ISSUE TITLE
Support for new Goerli testnet

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-common#29]
Goerli is a new - currently still experimental - cross-client PoA network, see https://github.com/goerli/testnet for information on network setup, genesis information and bootnodes.

Along with Goerli setup there is also some reactivation and new discussion here https://github.com/ethereum/EIPs/issues/1085 around a common genesis file format. We should actively engage, integrate stuff here (minimally e.g. the terminology) which is settled and contribute with ideas where there is still need for discussion. 

Integration here would be a separate issue, generally Goerli support and genesis file format integration is complementary.

**Comment by holgerd77** [comment]
Note: "without further references" should be read along "supported" and not "coming from", so "without further references existing on the client repo". 😄

**Comment by vpulim** [comment]
All networks are automatically supported so no separate release is needed on the client. You can verify by running client with the ``--help`` flag, which will list all known networks.

I will still probably modify the client's `package.json` to explicitly use version `0.6.1` of `common` just to make it clear.

**Comment by holgerd77** [comment]
Yes, that probably makes sense. Eventually also useful to explicitly list the "officially" supported networks in the docs, so that people are aware of what's possible and has been tested to some extend (maybe also add at least one test case to the unit tests for each network? Have no insight if the structure of the tests allow for such level of liveness for test runs.).
