### ISSUE TITLE
Add Kovan hardfork blocks

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-common#57]
When I set up this library I left out the Kovan hardfork blocks - see [here](https://github.com/ethereumjs/ethereumjs-common/blob/master/src/chains/kovan.json#L16) - simply because I didn't find them online on first sight.

These should be added, shouldn't be such a thing, eventually grabbable by some [Parity Ethereum](https://github.com/paritytech/parity-ethereum) code search or something.

**Comment by rkernegger** [comment]
This is what I found by searching through the release notes of parity:

St. Petersburg:
Block nr: 10255201

Constantinople
Block nr: 9200000

Byzantium
Block nr: 5067000

**Comment by rkernegger** [comment]
Also this can be found in https://github.com/paritytech/parity-ethereum/blob/master/ethcore/res/ethereum/kovan.json (I converted the hex values):

```
"params": {
  "networkID": "42",
  "forkBlock": "9922268",
  "eip155Transition": "1000000",
  "eip98Transition": "0x0",
  "eip140Transition": "5067000",
  "eip211Transition": "5067000",
  "eip214Transition": "5067000",
  "eip658Transition": "5067000",
  "wasmActivationTransition": "6600000",
  "eip145Transition": "9200000",
  "eip1014Transition": "9200000",
  "eip1052Transition": "9200000",
  "eip1283Transition": "9200000",
  "eip1283DisableTransition": "10255201",
  "kip4Transition": "9200000",
  "kip6Transition": "9200000"
}
```
