### ISSUE TITLE
TypeError: Common is not a constructor

### ISSUE THREAD

**Issue by mobiman1** [ethereumjs/ethereumjs-common#67]
```
const Common = require('ethereumjs-common');

// Instantiate with only the chain
let c = new Common('ropsten');

```
This keeps giving me this error:
```
let c = new Common('ropsten');
        ^

TypeError: Common is not a constructor
```

**Comment by s1na** [comment]
Try:

```typescript
const Common = require('ethereumjs-common').Common;
```

Refer to release [changelog](https://github.com/ethereumjs/ethereumjs-common/releases/tag/v1.0.0) for more info.

**Comment by mobiman1** [comment]
> Try:
> 
> ```ts
> const Common = require('ethereumjs-common').Common;
> ```
> 
> Refer to release [changelog](https://github.com/ethereumjs/ethereumjs-common/releases/tag/v1.0.0) for more info.

Thanks for the link. const Common = require('ethereumjs-common').default fixed it for me.
